### ISSUE TITLE
Namespace conflict with older project

### ISSUE THREAD

**Issue by pyhedgehog** [chaosmail/python-fs#3]
Sorry guys, but `fs` was already-used for [`pyFilesystem`](https://pypi.python.org/pypi/fs) project started around [2008](https://code.google.com/archive/p/pyfilesystem/downloads).

**Comment by chaosmail** [comment]
Hi @pyhedgehog 
I didn't thought it is a problem because the package is called `pyfs` on pypi.
Best,
Christoph

**Comment by pyhedgehog** [comment]
What will do `import fs` when both are installed?

**Comment by chaosmail** [comment]
Hi @pyhedgehog 

Yeah sure, the guys who install the packages should know what they are doing and what they are installing - so `import fs` will load the module from the first package it found on the disk.

I don't want to sound rude and I appreciate the discussion; this were my points considering the name `fs`

* it's short and equivalent to node.js, so very convenient
* the target audience (beginners, scientific computing, and some others) for the package is different to pyFilesystem (developers, system administrators, and some others)
* i didn't found any information that says you should not choose the same module name

Best,
Christoph

**Comment by pyhedgehog** [comment]
Your arguments seems correct. So I can only add that this possible conflict should be documented.

**Comment by lurch** [comment]
I just came across the problem myself ;-)

I wondered if there was a solution, but it [seems not](http://stackoverflow.com/a/11453972). According to [this](http://stackoverflow.com/questions/27532112/how-to-handle-python-packages-with-conflicting-names) the only real workaround is using virtualenvs.
