### ISSUE TITLE
Name class with other python library

### ISSUE THREAD

**Issue by guettli** [chaosmail/python-fs#4]
I was told this project has a name clash with an other:

http://softwarerecs.stackexchange.com/a/26670/1585

I compared both. The other has more commits and more contributors.

Would it be possible for you to change the name?

**Comment by chaosmail** [comment]
Hi @guettli,
I understand that name clashes with other libraries are not good. However, this library's purpose is to make it easy for python beginners (node developers, scientific researchers, ..) to access the file system like in a unix shell. Unfortunately, `fs` seems to be the best and most common name for filesystem modules.

When choosing a name for the module, I didn't find any pep conventions of avoiding name clashes on module level (only on package level). Therefore I decided to call it `fs` allthough there exists another library that defines the same module name (however this library is intended for a complete different audience and there are partially no usecases to use both at the same time).

I don't want to sound rude, unprofessional nor unwilling to help improving the python ecosystem - but I would really like to keep the module name. I think it is very important to make python easy to get started for newbies, and this lib (and some of my other repos) should hlep to achieve this.

I am open for discussion and your opinion on this.

Best,
Christoph
