### ISSUE TITLE
problem with relative paths

### ISSUE THREAD

**Issue by geoHeil** [chaosmail/python-fs#6]
`fs.exists('~/')` returns false on a mac

**Comment by chaosmail** [comment]
doesn't work on linux neither, because python doesn't expand `~` (source [stackoverflow](http://stackoverflow.com/questions/2057045/python-os-makedirs-dont-understand-in-my-path)). As a workaround you can use `fs.home()` to get the path of your home directory manually.

**Comment by geoHeil** [comment]
I see. 

For the record: this works nicely: 
 - expand the path os.path.expanduser("~/my/path/toFile.xy")
 - use fs library

**Comment by chaosmail** [comment]
We could auto-expand every path for convenience, what do you think?

**Comment by geoHeil** [comment]
Would be awesome.
